server:
  port: 9003

spring:
  application:
    name: speaking-service

  datasource:
    url: jdbc:postgresql://localhost:5432/english_learning
    username: postgres
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
